### ISSUE TITLE
Media Centre HAT not working on RPi4 with Buster

### ISSUE THREAD

**Issue by ojtramp** [PiSupply/Media-Center-HAT#13]
I've tried setting up the Media Centre HAT but cannot get the TFT screen to function at all. The touch control works out of the box and the rotation of the touch controls also functions after the setup but I haven't seen anything on the screen itself.

I've had a go using the [Pi Supply tutorials][1], and the ones referenced [here][2].

Originally I tried to set this up in Ubuntu (not officially supported) but have also not managed to get it working with Raspberry Pi OS Lite/Normal/Full, LibreELEC and even the latest image from [here][3]. 

The only error I see when the script runs is:
`E: Unable to locate package rbp-userland-dev-osmc` but on the OSMC website it says that it hasnt been updated for the Raspberry Pi 4, and Pi Supply say that they have tested their setup on Buster and say that this HAT is compatible with the Raspberry Pi 4 **so I think this is an optional package?** I have been unable to find a repository to install it on my device.

On the Raspberry Pi configuration settings I've enabled all interfaces (apart from SSH) to see if that made any difference but it didn't.

Any help people have on this would be great! In theory this is meant to be easy so I have no idea how I've managed to make it so complicated.

<hr>

***OS and Kernel Version***

    pi@raspberrypi:~ $ cat /etc/os-release
    PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
    NAME="Raspbian GNU/Linux"
    VERSION_ID="10"
    VERSION="10 (buster)"
    VERSION_CODENAME=buster
    ID=raspbian
    ID_LIKE=debian
    HOME_URL="http://www.raspbian.org/"
    SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
    BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
    pi@raspberrypi:~ $ uname -r
    5.4.79-v7l+

<hr>

***Pi Supply automated Script output***

    pi@raspberrypi:~ $ sudo su -c "bash <(wget -qO- https://pisupp.ly/mediacentersoftware)" root
    Hit:1 http://raspbian.raspberrypi.org/raspbian buster InRelease
    Hit:2 http://archive.raspberrypi.org/debian buster InRelease
    Reading package lists... Done
    Select one of the options below:
    [0] - Portrait
    [90] - Horizontal (Default)
    [180] - Portrait Reverse
    [270] - Horizontal Reverse
    Option: 90
    EEPROM Loaded
    --- /usr/share/X11/xorg.conf.d/ ---
    
    -layout TFT
    -layout HDMI (Select for fbcp use)
    -layout HDMITFT
    When -layout is not set in lightdm, the first is used: TFT
    Select your prefered layout:
    1. TFT Output Only
    2. HDMI Output Only (select for fbcp)
    3. HDMI(Primary) & TFT(extension) 
    Option(1-3):2
    Activate the console on the TFT display? y/n n
    Install fbcp (Framebuffer Copy)? y/n y
    --- Installing fbcp ---
    Installing FBCP on OMSC
    Reading package lists... Done
    Building dependency tree       
    Reading state information... Done
    E: Unable to locate package rbp-userland-dev-osmc
    Reading package lists... Done
    Building dependency tree       
    Reading state information... Done
    build-essential is already the newest version (12.6).
    git is already the newest version (1:2.20.1-2+deb10u3).
    The following additional packages will be installed:
      cmake-data libjsoncpp1 librhash0 libuv1
    Suggested packages:
      cmake-doc ninja-build
    The following NEW packages will be installed:
      cmake cmake-data libjsoncpp1 librhash0 libuv1
    0 upgraded, 5 newly installed, 0 to remove and 0 not upgraded.
    Need to get 4,330 kB of archives.
    After this operation, 21.8 MB of additional disk space will be used.
    Get:1 http://raspbian.mirror.uk.sargasso.net/raspbian buster/main armhf cmake-data all 3.13.4-1 [1,476 kB]
    Get:2 http://raspbian.mirror.uk.sargasso.net/raspbian buster/main armhf libjsoncpp1 armhf 1.7.4-3 [66.2 kB]
    Get:3 http://raspbian.mirror.uk.sargasso.net/raspbian buster/main armhf librhash0 armhf 1.3.8-1 [132 kB]
    Get:4 http://raspbian.mirror.uk.sargasso.net/raspbian buster/main armhf libuv1 armhf 1.24.1-1 [96.7 kB]
    Get:5 http://raspbian.mirror.uk.sargasso.net/raspbian buster/main armhf cmake armhf 3.13.4-1 [2,559 kB]
    Fetched 4,330 kB in 1s (4,309 kB/s)
    Selecting previously unselected package cmake-data.
    (Reading database ... 98393 files and directories currently installed.)
    Preparing to unpack .../cmake-data_3.13.4-1_all.deb ...
    Unpacking cmake-data (3.13.4-1) ...
    Selecting previously unselected package libjsoncpp1:armhf.
    Preparing to unpack .../libjsoncpp1_1.7.4-3_armhf.deb ...
    Unpacking libjsoncpp1:armhf (1.7.4-3) ...
    Selecting previously unselected package librhash0:armhf.
    Preparing to unpack .../librhash0_1.3.8-1_armhf.deb ...
    Unpacking librhash0:armhf (1.3.8-1) ...
    Selecting previously unselected package libuv1:armhf.
    Preparing to unpack .../libuv1_1.24.1-1_armhf.deb ...
    Unpacking libuv1:armhf (1.24.1-1) ...
    Selecting previously unselected package cmake.
    Preparing to unpack .../cmake_3.13.4-1_armhf.deb ...
    Unpacking cmake (3.13.4-1) ...
    Setting up libuv1:armhf (1.24.1-1) ...
    Setting up librhash0:armhf (1.3.8-1) ...
    Setting up cmake-data (3.13.4-1) ...
    Setting up libjsoncpp1:armhf (1.7.4-3) ...
    Setting up cmake (3.13.4-1) ...
    Processing triggers for man-db (2.8.5-2) ...
    Processing triggers for libc-bin (2.28-10+rpi1) ...
    Cloning into 'rpi-fbcp'...
    remote: Enumerating objects: 7, done.
    remote: Counting objects: 100% (7/7), done.
    remote: Compressing objects: 100% (5/5), done.
    remote: Total 7 (delta 1), reused 6 (delta 1), pack-reused 0
    Unpacking objects: 100% (7/7), done.
    -- The C compiler identification is GNU 8.3.0
    -- The CXX compiler identification is GNU 8.3.0
    -- Check for working C compiler: /usr/bin/cc
    -- Check for working C compiler: /usr/bin/cc -- works
    -- Detecting C compiler ABI info
    -- Detecting C compiler ABI info - done
    -- Detecting C compile features
    -- Detecting C compile features - done
    -- Check for working CXX compiler: /usr/bin/c++
    -- Check for working CXX compiler: /usr/bin/c++ -- works
    -- Detecting CXX compiler ABI info
    -- Detecting CXX compiler ABI info - done
    -- Detecting CXX compile features
    -- Detecting CXX compile features - done
    -- Configuring done
    -- Generating done
    -- Build files have been written to: /tmp/rpi-fbcp/build
    Scanning dependencies of target fbcp
    [ 50%] Building C object CMakeFiles/fbcp.dir/main.c.o
    [100%] Linking C executable fbcp
    [100%] Built target fbcp
    Enable automatic startup of fbcp on boot? y/n y
    Note: The console output on the TFT display will be disabled.
    Install xinput-calibrator? y/n n
    Enable onboard Joystick/Buttons? y/n n
    Configure MCH IR Remote? y/n n
    Reboot the system now? y/n

  [1]: https://github.com/PiSupply/Media-Center-HAT
  [2]: https://learn.watterott.com/hats/rpi-display/fbtft-install/
  [3]: https://learn.watterott.com/hats/rpi-display/sd-image/

**Comment by tvoverbeek** [comment]
On raspberry-Pi-OS you should not see a reference to OSMC when installing fbcp.
You have the main display output on HDMI and rely on fbcp to copy it to the TFT display.
Is fbcp runing?
To test start it manually 'sudo fbcp &'

**Comment by ojtramp** [comment]
So I dont think it's running on startup, I've added my /boot/config.txt below.
When I run the command sudo fbcp &, it returns [1] PID as below.

pi@raspberrypi:~ $ sudo fbcp &
[1] 1328

**/boot/config/.txt**
```

# For more options and information see
# http://rpf.io/configtxt
# Some settings may impact device functionality. See link above for details

# uncomment if you get no picture on HDMI for a default "safe" mode
#hdmi_safe=1

# uncomment this if your display has a black border of unused pixels visible
# and your display can output without overscan
#disable_overscan=1

# uncomment the following to adjust overscan. Use positive numbers if console
# goes off screen, and negative if there is too much border
#overscan_left=16
#overscan_right=16
#overscan_top=16
#overscan_bottom=16

# uncomment to force a console size. By default it will be display's size minus
# overscan.
#framebuffer_width=1280
#framebuffer_height=720

# uncomment if hdmi display is not detected and composite is being output
#hdmi_force_hotplug=1

# uncomment to force a specific HDMI mode (this will force VGA)
#hdmi_group=1
#hdmi_mode=1

# uncomment to force a HDMI mode rather than DVI. This can make audio work in
# DMT (computer monitor) modes
#hdmi_drive=2

# uncomment to increase signal to HDMI, if you have interference, blanking, or
# no display
#config_hdmi_boost=4

# uncomment for composite PAL
#sdtv_mode=2

#uncomment to overclock the arm. 700 MHz is the default.
#arm_freq=800

# Uncomment some or all of these to enable the optional hardware interfaces
dtparam=i2c_arm=on
#dtparam=i2s=on
dtparam=spi=on

# Uncomment this to enable infrared communication.
#dtoverlay=gpio-ir,gpio_pin=17
#dtoverlay=gpio-ir-tx,gpio_pin=18

# Additional overlays and parameters are documented /boot/overlays/README

# Enable audio (loads snd_bcm2835)
dtparam=audio=on

[pi4]
# Enable DRM VC4 V3D driver on top of the dispmanx display stack
dtoverlay=vc4-fkms-v3d
max_framebuffers=2

[all]
#dtoverlay=vc4-fkms-v3d
start_x=1
gpu_mem=128
enable_uart=1
dtoverlay=w1-gpio

```

**Comment by ojtramp** [comment]
So I've managed to fix it.

I went through the manual process again and had to add a few stages / install some drivers / etc. I used the instructions from this [link](https://github.com/ssvb/xf86-video-fbturbo/wiki/Installation) to get the display drivers I needed.
```
sudo apt-get install git build-essential xorg-dev xutils-dev x11proto-dri2-dev
sudo apt-get install libltdl-dev libtool automake libdrm-dev
git clone https://github.com/ssvb/xf86-video-fbturbo.git
cd xf86-video-fbturbo
autoreconf -vi
./configure --prefix=/usr
make
sudo make install
sudo cp xorg.conf /etc/X11/xorg.conf
```

I then edited the configuration files at these locations (they're slightly different from the ones listed in the manual guide).

```
sudo nano /etc/X11/xorg.conf 
sudo nano /etc/lightdm/lightdm.conf 
```

Hope that helps someone work out where the automated script is going wrong for me (hopefully It was just a unique issue to me, but if not maybe this will help!).

**Comment by mutipg** [comment]
I'm not good in Linux, but I'm trying do my best. I still have a problem with start Media Centre HAT on RPi4 with Buster.
- I had installed it with automated script,
- I also make steps from post above https://github.com/PiSupply/Media-Center-HAT/issues/13#issuecomment-743909451
- `sudo apt-get update` + `sudo apt-get upgrade`

After that Media Center HAT is probably working fine because after Ctrl+Alt+F2 I can see console, but it cannot start 'startx'. I see only blinking cursor on screen. I attached also Xorg log file - there is a line which IMO could be helpful:
`[    10.864] (EE) Screen 0 deleted because of no matching config section.`

@ojtramp, you wrote above:
> I then edited the configuration files at these locations (they're slightly different from the ones listed in the manual guide).
> ```
> sudo nano /etc/X11/xorg.conf 
> sudo nano /etc/lightdm/lightdm.conf 
> ```
> Hope that helps someone work out where the automated script is going wrong for me (hopefully It was just a unique issue to me, but if not maybe this will help!).

Could you help me and give me a hint what did you changed in these files? My files looks like below and I can't find what to change in them.

---
### OS and Kernel Version
```
cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
```
---
### /etc/X11/xorg.conf
```
Section "Device"
        Identifier      "Allwinner A10/A13 FBDEV"
        Driver          "fbturbo"
        Option          "fbdev" "/dev/fb0"

        Option          "SwapbuffersWait" "true"
EndSection
```
---
### /etc/lightdm/lightdm.conf
```
#
# General configuration
#
# start-default-seat = True to always start one seat if none are defined in the configuration
# greeter-user = User to run greeter as
# minimum-display-number = Minimum display number to use for X servers
# minimum-vt = First VT to run displays on
# lock-memory = True to prevent memory from being paged to disk
# user-authority-in-system-dir = True if session authority should be in the system location
# guest-account-script = Script to be run to setup guest account
# logind-check-graphical = True to on start seats that are marked as graphical by logind
# log-directory = Directory to log information to
# run-directory = Directory to put running state in
# cache-directory = Directory to cache to
# sessions-directory = Directory to find sessions
# remote-sessions-directory = Directory to find remote sessions
# greeters-directory = Directory to find greeters
# backup-logs = True to move add a .old suffix to old log files when opening new ones
# dbus-service = True if LightDM provides a D-Bus service to control it
#
[LightDM]
#start-default-seat=true
#greeter-user=lightdm
#minimum-display-number=0
#minimum-vt=7
#lock-memory=true
#user-authority-in-system-dir=false
#guest-account-script=guest-account
#logind-check-graphical=false
#log-directory=/var/log/lightdm
#run-directory=/var/run/lightdm
#cache-directory=/var/cache/lightdm
#sessions-directory=/usr/share/lightdm/sessions:/usr/share/xsessions:/usr/share/wayland-sessions
#remote-sessions-directory=/usr/share/lightdm/remote-sessions
#greeters-directory=$XDG_DATA_DIRS/lightdm/greeters:$XDG_DATA_DIRS/xgreeters
#backup-logs=true
#dbus-service=true

#
# Seat configuration
#
# Seat configuration is matched against the seat name glob in the section, for example:
# [Seat:*] matches all seats and is applied first.
# [Seat:seat0] matches the seat named "seat0".
# [Seat:seat-thin-client*] matches all seats that have names that start with "seat-thin-client".
#
# type = Seat type (local, xremote, unity)
# pam-service = PAM service to use for login
# pam-autologin-service = PAM service to use for autologin
# pam-greeter-service = PAM service to use for greeters
# xserver-backend = X backend to use (mir)
# xserver-command = X server command to run (can also contain arguments e.g. X -special-option)
# xmir-command = Xmir server command to run (can also contain arguments e.g. Xmir -special-option)
# xserver-config = Config file to pass to X server
xserver-layout=TFT
# xserver-allow-tcp = True if TCP/IP connections are allowed to this X server
# xserver-share = True if the X server is shared for both greeter and session
# xserver-hostname = Hostname of X server (only for type=xremote)
# xserver-display-number = Display number of X server (only for type=xremote)
# xdmcp-manager = XDMCP manager to connect to (implies xserver-allow-tcp=true)
# xdmcp-port = XDMCP UDP/IP port to communicate on
# xdmcp-key = Authentication key to use for XDM-AUTHENTICATION-1 (stored in keys.conf)
# unity-compositor-command = Unity compositor command to run (can also contain arguments e.g. unity-system-compositor -special-option)
# unity-compositor-timeout = Number of seconds to wait for compositor to start
# greeter-session = Session to load for greeter
# greeter-hide-users = True to hide the user list
# greeter-allow-guest = True if the greeter should show a guest login option
# greeter-show-manual-login = True if the greeter should offer a manual login option
# greeter-show-remote-login = True if the greeter should offer a remote login option
# user-session = Session to load for users
# allow-user-switching = True if allowed to switch users
# allow-guest = True if guest login is allowed
# guest-session = Session to load for guests (overrides user-session)
# session-wrapper = Wrapper script to run session with
# greeter-wrapper = Wrapper script to run greeter with
# guest-wrapper = Wrapper script to run guest sessions with
# display-setup-script = Script to run when starting a greeter session (runs as root)
# display-stopped-script = Script to run after stopping the display server (runs as root)
# greeter-setup-script = Script to run when starting a greeter (runs as root)
# session-setup-script = Script to run when starting a user session (runs as root)
# session-cleanup-script = Script to run when quitting a user session (runs as root)
# autologin-guest = True to log in as guest by default
# autologin-user = User to log in with by default (overrides autologin-guest)
# autologin-user-timeout = Number of seconds to wait before loading default user
# autologin-session = Session to load for automatic login (overrides user-session)
# autologin-in-background = True if autologin session should not be immediately activated
# exit-on-failure = True if the daemon should exit if this seat fails
#
[Seat:*]
#type=local
#pam-service=lightdm
#pam-autologin-service=lightdm-autologin
#pam-greeter-service=lightdm-greeter
#xserver-backend=
#xserver-command=X
#xmir-command=Xmir
#xserver-config=
xserver-layout=TFT
#xserver-allow-tcp=false
#xserver-share=true
#xserver-hostname=
#xserver-display-number=
#xdmcp-manager=
#xdmcp-port=177
#xdmcp-key=
#unity-compositor-command=unity-system-compositor
#unity-compositor-timeout=60
greeter-session=pi-greeter
greeter-hide-users=false
#greeter-allow-guest=true
#greeter-show-manual-login=false
#greeter-show-remote-login=true
#user-session=default
#allow-user-switching=true
#allow-guest=true
#guest-session=
#session-wrapper=lightdm-session
#greeter-wrapper=
#guest-wrapper=
display-setup-script=/usr/share/dispsetup.sh
#display-stopped-script=
#greeter-setup-script=
#session-setup-script=
#session-cleanup-script=
#autologin-guest=false
autologin-user=pi
#autologin-user-timeout=0
#autologin-in-background=false
#autologin-session=
#exit-on-failure=false

#
# XDMCP Server configuration
#
# enabled = True if XDMCP connections should be allowed
# port = UDP/IP port to listen for connections on
# listen-address = Host/address to listen for XDMCP connections (use all addresses if not present)
# key = Authentication key to use for XDM-AUTHENTICATION-1 or blank to not use authentication (stored in keys.conf)
# hostname = Hostname to report to XDMCP clients (defaults to system hostname if unset)
#
# The authentication key is a 56 bit DES key specified in hex as 0xnnnnnnnnnnnnnn.  Alternatively
# it can be a word and the first 7 characters are used as the key.
#
[XDMCPServer]
#enabled=false
#port=177
#listen-address=
#key=
#hostname=

#
# VNC Server configuration
#
# enabled = True if VNC connections should be allowed
# command = Command to run Xvnc server with
# port = TCP/IP port to listen for connections on
# listen-address = Host/address to listen for VNC connections (use all addresses if not present)
# width = Width of display to use
# height = Height of display to use
# depth = Color depth of display to use
#
[VNCServer]
#enabled=false
#command=Xvnc
#port=5900
#listen-address=
#width=1024
#height=768
#depth=8
```
---
### /var/log/Xorg.0.log
```
[    10.852] 
X.Org X Server 1.20.4
X Protocol Version 11, Revision 0
[    10.853] Build Operating System: Linux 5.4.0-72-generic armv8l Raspbian
[    10.853] Current Operating System: Linux raspberrypi 5.10.103-v7l+ #1529 SMP Tue Mar 8 12:24:00 GMT 2022 armv7l
[    10.853] Kernel command line: coherent_pool=1M 8250.nr_uarts=0 snd_bcm2835.enable_compat_alsa=0 snd_bcm2835.enable_hdmi=1  smsc95xx.macaddr=DC:A6:32:A5:CA:3F vc_mem.mem_base=0x3ec00000 vc_mem.mem_size=0x40000000  console=ttyS0,115200 console=tty1 root=PARTUUID=250dc57a-02 rootfstype=ext4 fsck.repair=yes rootwait splash plymouth.ignore-serial-consoles
[    10.853] Build Date: 04 January 2022  10:05:34AM
[    10.853] xorg-server 2:1.20.4-1+rpt4+deb10u4 (https://www.debian.org/support) 
[    10.853] Current version of pixman: 0.36.0
[    10.853] 	Before reporting problems, check http://wiki.x.org
	to make sure that you have the latest version.
[    10.853] Markers: (--) probed, (**) from config file, (==) default setting,
	(++) from command line, (!!) notice, (II) informational,
	(WW) warning, (EE) error, (NI) not implemented, (??) unknown.
[    10.853] (==) Log file: "/var/log/Xorg.0.log", Time: Tue Apr  5 16:32:08 2022
[    10.853] (==) Using config file: "/etc/X11/xorg.conf"
[    10.853] (==) Using system config directory "/usr/share/X11/xorg.conf.d"
[    10.854] (++) ServerLayout "TFT"
[    10.854] (**) |-->Screen "ScreenTFT" (0)
[    10.854] (**) |   |-->Monitor "MonitorTFT"
[    10.855] (**) |   |-->Device "DeviceTFT"
[    10.855] (**) |   |-->GPUDevice "DeviceTFT"
[    10.855] (**) |   |-->GPUDevice "Allwinner A10/A13 FBDEV"
[    10.855] (**) Option "BlankTime" "10"
[    10.855] (==) Automatically adding devices
[    10.855] (==) Automatically enabling devices
[    10.855] (==) Automatically adding GPU devices
[    10.855] (==) Max clients allowed: 256, resource mask: 0x1fffff
[    10.855] (WW) The directory "/usr/share/fonts/X11/misc" does not exist.
[    10.855] 	Entry deleted from font path.
[    10.855] (WW) The directory "/usr/share/fonts/X11/cyrillic" does not exist.
[    10.855] 	Entry deleted from font path.
[    10.855] (WW) The directory "/usr/share/fonts/X11/100dpi/" does not exist.
[    10.855] 	Entry deleted from font path.
[    10.855] (WW) The directory "/usr/share/fonts/X11/75dpi/" does not exist.
[    10.855] 	Entry deleted from font path.
[    10.855] (WW) The directory "/usr/share/fonts/X11/Type1" does not exist.
[    10.855] 	Entry deleted from font path.
[    10.855] (WW) The directory "/usr/share/fonts/X11/100dpi" does not exist.
[    10.855] 	Entry deleted from font path.
[    10.855] (WW) The directory "/usr/share/fonts/X11/75dpi" does not exist.
[    10.855] 	Entry deleted from font path.
[    10.855] (==) FontPath set to:
	built-ins
[    10.855] (==) ModulePath set to "/usr/lib/xorg/modules"
[    10.855] (II) The server relies on udev to provide the list of input devices.
	If no devices become available, reconfigure udev or disable AutoAddDevices.
[    10.856] (II) Loader magic: 0x1fdf80
[    10.856] (II) Module ABI versions:
[    10.856] 	X.Org ANSI C Emulation: 0.4
[    10.856] 	X.Org Video Driver: 24.0
[    10.856] 	X.Org XInput driver : 24.1
[    10.856] 	X.Org Server Extension : 10.0
[    10.857] (++) using VT number 7

[    10.857] (II) systemd-logind: logind integration requires -keeptty and -keeptty was not provided, disabling logind integration
[    10.858] (II) xfree86: Adding drm device (/dev/dri/card1)
[    10.859] (II) xfree86: Adding drm device (/dev/dri/card0)
[    10.860] (II) no primary bus or device found
[    10.860] 	falling back to /sys/devices/platform/gpu/drm/card1
[    10.860] (II) LoadModule: "glx"
[    10.860] (II) Loading /usr/lib/xorg/modules/extensions/libglx.so
[    10.863] (II) Module glx: vendor="X.Org Foundation"
[    10.863] 	compiled for 1.20.4, module version = 1.0.0
[    10.863] 	ABI class: X.Org Server Extension, version 10.0
[    10.863] (II) LoadModule: "fbturbo"
[    10.863] (II) Loading /usr/lib/xorg/modules/drivers/fbturbo_drv.so
[    10.863] (II) Module fbturbo: vendor="X.Org Foundation"
[    10.863] 	compiled for 1.20.4, module version = 0.5.1
[    10.863] 	Module class: X.Org Video Driver
[    10.863] 	ABI class: X.Org Video Driver, version 24.0
[    10.863] (II) FBTURBO: driver for framebuffer: fbturbo
[    10.864] (WW) Falling back to old probe method for fbturbo
[    10.864] (II) Loading sub module "fbdevhw"
[    10.864] (II) LoadModule: "fbdevhw"
[    10.864] (II) Loading /usr/lib/xorg/modules/libfbdevhw.so
[    10.864] (II) Module fbdevhw: vendor="X.Org Foundation"
[    10.864] 	compiled for 1.20.4, module version = 0.0.2
[    10.864] 	ABI class: X.Org Video Driver, version 24.0
[    10.864] (EE) open /dev/fb1: No such file or directory
[    10.864] (EE) open /dev/fb1: No such file or directory
[    10.864] (II) FBTURBO(0): using /dev/fb0
[    10.864] (EE) Screen 0 deleted because of no matching config section.
[    10.864] (II) UnloadModule: "fbturbo"
[    10.864] (II) UnloadSubModule: "fbdevhw"
[    10.864] (EE) Device(s) detected, but none match those in the config file.
[    10.864] (EE) 
Fatal server error:
[    10.865] (EE) no screens found(EE) 
[    10.865] (EE) 
Please consult the The X.Org Foundation support 
	 at http://wiki.x.org
 for help. 
[    10.865] (EE) Please also check the log file at "/var/log/Xorg.0.log" for additional information.
[    10.865] (EE) 
[    10.865] (EE) Server terminated with error (1). Closing log file.
```
