### ISSUE TITLE
add images here

### ISSUE THREAD

**Issue by shawaj** [PiSupply/Media-Center-HAT#4]
use this issue to add images

![mc_hat](https://user-images.githubusercontent.com/3359418/34419690-29629dd6-ebfd-11e7-9597-b616a44c72d4.jpg)
![mc_hat_assembly_bottom 1](https://user-images.githubusercontent.com/3359418/34419700-34014576-ebfd-11e7-8b69-31cc94648cf0.jpg)

**Comment by shawaj** [comment]
@francesco-vannini FYI.

Closing this issue now but can still be used

**Comment by francesco-vannini** [comment]
![mediacenterhat](https://user-images.githubusercontent.com/16068311/35614771-0edeffce-0668-11e8-824d-59421747a844.png)

**Comment by francesco-vannini** [comment]
![mch-overview](https://user-images.githubusercontent.com/16068311/36383426-06daa938-1584-11e8-9adc-f9e1125aa10d.png)

**Comment by francesco-vannini** [comment]
![mch-ics](https://user-images.githubusercontent.com/16068311/36383446-10b64c82-1584-11e8-9f4b-33c080356dd0.png)

**Comment by francesco-vannini** [comment]
![mch-xinput-calibration](https://user-images.githubusercontent.com/16068311/36484231-77d98194-1710-11e8-8dc9-caaf13e0bd40.png)

**Comment by ChristopherRush** [comment]
![Media-Center-HAT](https://user-images.githubusercontent.com/1878314/61450620-6136c280-a94f-11e9-9b57-bd147ad864c7.png)

**Comment by ChristopherRush** [comment]
![pisupply-media-center-hat-github-banner](https://user-images.githubusercontent.com/1878314/73882204-8fcbaa80-4859-11ea-87c1-692a14d2118b.png)

**Comment by shawaj** [comment]
![88x31](https://user-images.githubusercontent.com/3359418/82903405-ce948600-9f58-11ea-8125-b452a79a0b6b.png)
