### ISSUE TITLE
Change capacitive to resistive

### ISSUE THREAD

**Issue by shawaj** [PiSupply/Media-Center-HAT#8]
@ryanteck mentioned that we had incorrectly listed that the touch screen is capacitive rather than resistive in documentation and on the product descriptions and packaging. Need to update this

**Comment by ryanteck** [comment]
Updated the github

**Comment by shawaj** [comment]
Thanks @ryanteck 

Will work with @JohnWhiting to update on the packaging and the website 👌

**Comment by shawaj** [comment]
Added to Trello for @louisreed on the packaging and I just went to update the website just now and someone has already done it so will close this issue 👌
